run:
  timeout: 3m

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - deadcode
    - gosimple
    - errcheck
    - gocyclo
    - gosec
    - misspell

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  gocyclo:
    min-complexity: 15

  misspell:
    locale: US
